"""added lazy selection for user and deposits

Revision ID: 04844aee175f
Revises: fe041c2f01ee
Create Date: 2025-03-05 19:14:50.050535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04844aee175f'
down_revision: Union[str, None] = 'fe041c2f01ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
