"""changed table order to user_order

Revision ID: 7017e8115be7
Revises: a1b2c3d4e5f6
Create Date: 2025-03-21 14:40:44.008544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7017e8115be7"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Rename order table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_order",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("token", sa.VARCHAR(), nullable=False),
        sa.Column("position", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "id"),
    )
    op.drop_table("order")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Create old and drop new table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("position", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="order_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="order_pkey"),
    )
    op.drop_table("user_order")
    # ### end Alembic commands ###
