"""Remove token from user pool

Revision ID: d23e53e374ba
Revises: 9cf106d80ed0
Create Date: 2025-02-22 20:48:33.878922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23e53e374ba'
down_revision: Union[str, None] = '9cf106d80ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop token to user_pool"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pool', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Add token from user_pool"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
