"""empty message

Revision ID: 7bb8c6d1a644
Revises: 4af01f3b6056
Create Date: 2025-01-18 15:10:06.637162

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bb8c6d1a644"
down_revision = "4af01f3b6056"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Creates unique constrain over position_id and token_symbol in extra_deposits table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_position_token_uc", "extra_deposits", ["position_id", "token_symbol"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops unique constrain over position_id and token_symbol in extra_deposits table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_position_token_uc", "extra_deposits", type_="unique")
    # ### end Alembic commands ###
