"""change multiplier field type

Revision ID: cda4342b007d
Revises: 1a6fada80369
Create Date: 2024-12-07 12:37:05.550048

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cda4342b007d"
down_revision = "1a6fada80369"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade the database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "multiplier",
        existing_type=sa.INTEGER(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade the database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "multiplier",
        existing_type=sa.NUMERIC(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
