"""add postion columns

Revision ID: 1a6fada80369
Revises: 0537a9a5e841
Create Date: 2024-11-25 07:34:11.693095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6fada80369'
down_revision = '0537a9a5e841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('is_protection', sa.Boolean(), nullable=True))
    op.add_column('position', sa.Column('liquidation_bonus', sa.Float(), nullable=True))
    op.add_column('position', sa.Column('is_liquidated', sa.Boolean(), nullable=True))
    op.add_column('position', sa.Column('datetime_liquidation', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'datetime_liquidation')
    op.drop_column('position', 'is_liquidated')
    op.drop_column('position', 'liquidation_bonus')
    op.drop_column('position', 'is_protection')
    # ### end Alembic commands ###
