"""empty message

Revision ID: 9662d09015ae
Revises: 7bb8c6d1a644
Create Date: 2025-01-18 15:12:27.856559

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9662d09015ae"
down_revision = "7bb8c6d1a644"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Drops unique constraint on extra_deposits' table token_symbol field"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "extra_deposits_token_symbol_key", "extra_deposits", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Creates unique constraint on extra_deposits' table token_symbol field"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "extra_deposits_token_symbol_key", "extra_deposits", ["token_symbol"]
    )
    # ### end Alembic commands ###
