"""migration message

Revision ID: a50b7c912e8c
Revises: 9662d09015ae
Create Date: 2025-01-23 07:41:32.699318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50b7c912e8c'
down_revision = '9662d09015ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
