"""remove_airdrop

Revision ID: b6eaae01419c
Revises: cda4342b007d
Create Date: 2024-12-10 19:37:04.898405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6eaae01419c'
down_revision = 'cda4342b007d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_airdrop_is_claimed', table_name='airdrop')
    op.drop_index('ix_airdrop_user_id', table_name='airdrop')
    op.drop_table('airdrop')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('is_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('claimed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='airdrop_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='airdrop_pkey')
    )
    op.create_index('ix_airdrop_user_id', 'airdrop', ['user_id'], unique=False)
    op.create_index('ix_airdrop_is_claimed', 'airdrop', ['is_claimed'], unique=False)
    # ### end Alembic commands ###
