"""add referal model

Revision ID: c045e432555c
Revises: 9662d09015ae
Create Date: 2025-01-27 11:13:18.108241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c045e432555c'
down_revision = '9662d09015ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('referal_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referal_referal_id'), 'referal', ['referal_id'], unique=True)
    op.create_index(op.f('ix_referal_user_id'), 'referal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referal_user_id'), table_name='referal')
    op.drop_index(op.f('ix_referal_referal_id'), table_name='referal')
    op.drop_table('referal')
    # ### end Alembic commands ###
