"""Initial Migration

Revision ID: c2b9b806773d
Revises: c045e432555c
Create Date: 2025-03-28 17:14:08.273566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b9b806773d'
down_revision = 'c045e432555c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
