"""Fix margin position status

Revision ID: fe041c2f01ee
Revises: ec8fbaba3c97
Create Date: 2025-02-22 21:25:31.174042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe041c2f01ee'
down_revision: Union[str, None] = 'ec8fbaba3c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add status enum"""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Open', 'Closed', name='margin_position_status').create(op.get_bind())
    with op.batch_alter_table('margin_position', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Open', 'Closed', name='margin_position_status'),
               existing_nullable=False,
               postgresql_using='status::margin_position_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop status enum"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('margin_position', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Open', 'Closed', name='margin_position_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    sa.Enum('Open', 'Closed', name='margin_position_status').drop(op.get_bind())
    # ### end Alembic commands ###
